version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      target: final
    command: sh -c "cd app && ./web"
    ports:
      - "4000:4000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
      MYSQL_DB: snippetbox
  mysql:
    container_name: mysql-snippet
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    volumes:
      - snippet-db:/var/lib/mysql
volumes:
  snippet-db:
    