version: "3.9"
services:
  app:
    image: ghcr.io/pvmtriet232/snippetbox2:main
    working_dir: /app
    command: sh -c "./web"
    ports:
      - "4000:4000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
      MYSQL_DB: snippetbox
    depends_on:
      mysql:
        condition: service_healthy
        
  mysql:
    container_name: mysql-snippet
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-h", "mysql"]
      timeout: 3s
      retries: 3
