version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: base
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - appmysql
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DB: snippetbox
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - appmysql
volumes:
  mysql:

networks:
  appmysql:
    driver: bridge
    