apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: ap-southeast-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 
    volumeSize: 8
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 8

