apiVersion: v1
kind: Pod
metadata:
  labels:
    run: snippetbox
  name: snippetbox
  namespace: default
spec:
  containers:
  - name: snippetbox
    image: ghcr.io/pvmtriet232/snippetbox2:main
    command: 
    - ./web
    - -dsn=web:pass@tcp($(db_host))/snippetbox?parseTime=true
    envFrom: 
      - configMapRef:
          name: app-config
    imagePullPolicy: Always
    ports:
    - containerPort: 4000
      protocol: TCP
