apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  volumes:
    - name: initdb
      configMap:
        name: initdb-config
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: rootpassword
    - name: MYSQL_DATABASE
      value: snippetbox
    - name: MYSQL_USER
      value: web
    - name: MYSQL_PASSWORD
      value: pass
    image: mysql:latest
    name: mysql
    ports:
    - containerPort: 3306
    volumeMounts:
      - name: initdb
        mountPath: /docker-entrypoint-initdb.d
  restartPolicy: Always
