apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: rootpassword
    - name: MYSQL_DATABASE
      value: snippetbox
    - name: MYSQL_USER
      value: web
    - name: MYSQL_PASSWORD
      value: pass
    image: mysql:latest
    name: mysql
    ports:
    - containerPort: 3306
    volumesMounts:
      - name: initdb
        mouthPath: /docker-entrypoint-initdb.d
  restartPolicy: Always
volumes:
  - name: initdb
    configmap:
      name: initdb-config
