apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
status:
  loadBalancer: {}
---



apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: snippetbox
  name: snippetbox-sv
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    run: snippetbox
  type: LoadBalancer
status:
  loadBalancer: {}
