apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
status:
  loadBalancer: {}
---

apiVersion: v1
kind: Service
metadata:
  name: snippetbox-service
  labels:
    run: snippetbox
spec:
  ports:
    - port: 4000
  selector:
    run: snippetbox
    tier: frontend
  type: LoadBalancer

