apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/snippetbox2-default: "true"
        io.kompose.service: app
    spec:
      containers:
        - args:
            - sh
            - -c
            - ./web
          env:
            - name: MYSQL_DB
              value: snippetbox
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: pass
            - name: MYSQL_USER
              value: web
          image: ghcr.io/pvmtriet232/snippetbox2:main
          name: app
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
          resources: {}
          workingDir: /app
      restartPolicy: Always
status: {}
